config/routes.rb
Rails.application.routes.draw do
  resources :compras

   root 'compras#index'

end

app/models/compra.rb
class Compra < ActiveRecord::Base
  validates_presence_of :cuerpo, :message => '. Debes introducir una compra.'
  validates_uniqueness_of :cuerpo, :message => '. Ya existe una compra con el mismo nombre.'
  
  def esComprado
    if comprado
      return ""
    else
      return "PTE"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to compras_path, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to compras_path, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:cuerpo, :comprado)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/compras/_form.html.erb
<%= stylesheet_link_tag "styles" %>
<%= form_for(@compra) do |f| %>
  <% if @compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% @compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo, :class => "text_area" %>
  </div>
  <div class="field">
    <%= f.label :comprado %>
    <%= f.check_box :comprado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Modificando compra</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @compra %> |
<%= link_to 'Atrás', compras_path %>

app/views/compras/index.html.erb
<%= stylesheet_link_tag "styles" %>
<h1>Casa Rural</h1>
<h2>11-13 Octubre 2014</h2>

<div class="div_nota">
  <b>Nota: </b>
Llegaremos antes de comer el sábado y nos volvemos después de comer el domingo, por lo tanto tenemos:
<ul>
  <li>2 desayunos
    <span>Por aqui podemos comer pan, dulces y similares. Crepes o tortitas si se desean.</span>
    <br/>
  </li>
  <li>3 almuerzos
    <span>Para los almuerzos creo que el plato fuerte sería la carne. Acompañada de alguna ensalada, verde o de pimientos.</span>
    <br/>
  </li>
  <li>2 cenas
    <span>En las cenas cosillas más ligeras, como revueltos de patatas, esparragos... incluso una de las noches pizza</span>
    <br/>
  </li>
</ul>
Siempre para todas las comidas tenemos los embutidos, el queso, las patatas de paquete y porquerias similares.
</div>
<p/>
<table bgcolor="#D8D8D8">
  <thead>
    <tr>
      <th colspan="3">Listado de compra</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% cont = 0 %>
    <% @compras.order('cuerpo').each do |compra| %>
      <tr>
        <% cont += 1 %>
        <td><%= cont %></td>
        <td class="lb_cuerpo"><%= link_to compra.cuerpo , edit_compra_path(compra) %></td>
        <td class="lb_rojo"><%= compra.esComprado() %></td>
        <td><%= link_to 'Modificar', edit_compra_path(compra) %> <%= link_to 'Eliminar', compra, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<br>

<%= form_for([@compra, Compra.new]) do |f| %>
<p><%= f.label :cuerpo, "Nueva Compra" %><br />
  <%= f.text_area :cuerpo , :id => "area_cuerpo" %>
</p>
<p><%= f.submit "Añadir" %></p>
<% end %>

app/views/compras/new.html.erb
<h1>Nueva compra</h1>

<%= render 'form' %>

<%= link_to 'Atrás', compras_path %>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cuerpo:</strong>
  <%= @compra.cuerpo %>
</p>

<p>
  <strong>Comprado:</strong>
  <%= @compra.comprado %>
</p>

<%= link_to 'Editar', edit_compra_path(@compra) %> |
<%= link_to 'Atrás', compras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Casa Rural</title>
  <meta name="viewport" content="width=device-width"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Casa Rural</h1>
<%= link_to 'Lista de Compras', :controller => :compras, :action => :index %>